#!/usr/bin/env bash
#
# autoDev — convention auto-detector. Scans the TARGET repo for the house patterns
# a fresh-context dev agent would otherwise reinvent (generated types, design
# system/theme, data layer, testing) and emits a prescriptive markdown report.
# install.sh runs this and writes the result to .autodev/conventions.md, which the
# SessionStart hook injects (and autodev.md references) — so the dev persona inherits
# "use the generated types, use the theme" as BINDING context instead of hand-rolling
# types and hardcoding styles. The team's own AGENTS.md/CLAUDE.md still wins on conflict.
#
# Read-only on the repo. Usage: detect-conventions.sh <repo_path>
# Always prints SOMETHING (even "none detected → declare it"); never fails install.
set -uo pipefail

REPO="${1:-.}"
PKG="$REPO/package.json"

# dep present in dependencies or devDependencies?
have_dep() { [ -f "$PKG" ] && command -v jq >/dev/null 2>&1 && \
  jq -e --arg d "$1" '((.dependencies//{})+(.devDependencies//{}))|keys[]|select(test($d))' "$PKG" >/dev/null 2>&1; }
# a file matching glob-name exists somewhere sensible (not node_modules/dist)?
have_file() { find "$REPO" -maxdepth 3 \( -path '*/node_modules' -o -path '*/dist' -o -path '*/.git' \) -prune -o \
  -name "$1" -print 2>/dev/null | grep -q .; }

echo "# Detected project conventions (auto-generated by autoDev install)"
echo
echo "> Scanned \`$REPO\` at install time. **These are BINDING** where your own files are"
echo "> silent — the dev agent adopts them, never reinvents them. Re-generated on every"
echo "> \`install.sh\`. To refine or override, edit your **AGENTS.md / CLAUDE.md** (the team's"
echo "> own files are the top authority on conventions and win on conflict)."
echo

# ---- language / package manager / framework --------------------------------
echo "## Stack"
[ -f "$REPO/tsconfig.json" ] && echo "- **TypeScript** (\`tsconfig.json\`) — keep it type-safe; do not paper over types with \`any\`/\`as unknown\`."
if   [ -f "$REPO/bun.lockb" ];          then echo "- Package manager: **bun** — use \`bun\`."
elif [ -f "$REPO/pnpm-lock.yaml" ];     then echo "- Package manager: **pnpm** — use \`pnpm\`."
elif [ -f "$REPO/yarn.lock" ];          then echo "- Package manager: **yarn** — use \`yarn\`."
elif [ -f "$REPO/package-lock.json" ];  then echo "- Package manager: **npm** — use \`npm\`."; fi
have_dep '^react$'   && echo "- Framework: **React**."
have_dep '^vue$'     && echo "- Framework: **Vue**."
have_dep '^svelte$'  && echo "- Framework: **Svelte**."
have_dep '@angular/core' && echo "- Framework: **Angular**."
echo

# ---- TYPE GENERATION (the codegen gap) -------------------------------------
echo "## Types — source of truth (do NOT hand-roll these)"
TYPES_FOUND=0
if have_dep '@graphql-codegen' || have_file 'codegen.ts' || have_file 'codegen.yml' || have_file 'codegen.json' || have_file '*.generated.ts' || have_file '*.generated.tsx'; then
  echo "- **GraphQL code generation** detected (graphql-codegen / \`codegen.*\` / \`*.generated.ts\`)."
  echo "  → **Import the generated types** (\`*.generated.ts\` / \`__generated__/\`). **Never hand-write"
  echo "  GraphQL or schema-shaped types per component** — that's what forces \`as unknown\` casts and"
  echo "  duplicated types. Add an operation → run codegen, then import what it produces."
  TYPES_FOUND=1
fi
if have_file 'schema.prisma'; then
  echo "- **Prisma** (\`schema.prisma\`) → use the generated \`@prisma/client\` types; don't redeclare models."
  TYPES_FOUND=1
fi
if have_dep 'openapi-typescript' || have_dep '^orval$' || have_file 'openapi.*'; then
  echo "- **OpenAPI type generation** → import the generated API types; don't hand-type responses."
  TYPES_FOUND=1
fi
[ "$TYPES_FOUND" = 0 ] && echo "- ⚠️ No type-generation tool auto-detected. **Declare the type source-of-truth** in your AGENTS.md / CLAUDE.md (e.g. generated client types) so the agent doesn't invent per-component types."
echo

# ---- STYLING / DESIGN SYSTEM (the hardcoded-styles gap) --------------------
echo "## Styling — use the design system, do NOT hardcode"
STYLE_FOUND=0
if have_dep '@mui/material'; then
  echo "- **Material UI (MUI)** detected. → **Use the MUI theme** (\`useTheme\`/\`styled\`/\`sx\` with"
  echo "  theme tokens — \`theme.palette\`, \`theme.spacing\`). **Never hardcode** colors / spacing /"
  echo "  typography; if a token is missing, extend the theme, don't inline a literal."
  have_file 'theme.ts'  && echo "  (Theme file present — import and extend it.)"
  have_file 'theme.tsx' && echo "  (Theme file present — import and extend it.)"
  STYLE_FOUND=1
fi
if [ -f "$REPO/tailwind.config.js" ] || [ -f "$REPO/tailwind.config.ts" ] || have_file 'tailwind.config.*'; then
  echo "- **Tailwind** detected → use utility classes + the config's design tokens; no ad-hoc inline styles."
  STYLE_FOUND=1
fi
have_dep 'styled-components' && { echo "- **styled-components** → use the theme via \`ThemeProvider\`; no hardcoded literals."; STYLE_FOUND=1; }
have_dep '@emotion'          && { echo "- **Emotion** → theme tokens via the \`css\`/\`styled\` theme; no hardcoded literals."; STYLE_FOUND=1; }
have_dep '@chakra-ui'        && { echo "- **Chakra UI** → use theme tokens / style props; no hardcoded literals."; STYLE_FOUND=1; }
[ "$STYLE_FOUND" = 0 ] && echo "- ⚠️ No design system auto-detected. **Declare the styling convention** in your AGENTS.md / CLAUDE.md so the agent doesn't hardcode styles."
echo

# ---- data layer / testing --------------------------------------------------
echo "## Data layer & testing"
have_dep '@apollo/client'       && echo "- Data: **Apollo Client** — use its hooks/cache; follow existing query/fragment patterns."
have_dep '@tanstack/react-query' && echo "- Data: **TanStack Query** — use existing query keys/hooks."
have_dep '^urql$'               && echo "- Data: **urql** — follow existing client setup."
have_dep '^vitest$'   && echo "- Tests: **Vitest**."
have_dep '^jest$'     && echo "- Tests: **Jest**."
have_dep 'cypress'    && echo "- E2E: **Cypress**."
have_dep '@playwright/test' && echo "- E2E: **Playwright**."
echo

echo "## Always"
echo "- **Reuse before you write:** search for an existing component/hook/util that does the job"
echo "  before adding a new one. Duplicated logic / copy-pasted components are a defect, not a diff."
